/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.form;

import com.cafe.dao.DonViDao;
import com.cafe.dao.KhuVucDAO;
import com.cafe.model.DonVi;
import com.cafe.model.KhuVuc;
import com.cafe.utils.Auth;
import com.cafe.utils.MsgBox;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGHIA
 */
public class DonViJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonViJPanel
     */
    public DonViJPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtWebsite = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDonVi = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1536, 864));

        jPanel4.setBackground(new java.awt.Color(230, 213, 193));
        jPanel4.setPreferredSize(new java.awt.Dimension(1536, 864));

        jLabel33.setBackground(new java.awt.Color(97, 67, 67));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(97, 67, 67));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("QUẢN LÝ ĐƠN VỊ");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnTimKiem.setBackground(new java.awt.Color(191, 158, 117));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/search.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(97, 67, 67));
        jLabel35.setText("DANH SÁCH ĐƠN VỊ");

        jPanel2.setBackground(new java.awt.Color(230, 213, 193));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(97, 67, 67));
        jLabel32.setText("Mã đơn vị *");

        txtMaDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaDV.setPreferredSize(new java.awt.Dimension(300, 22));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(97, 67, 67));
        jLabel31.setText("Tên đơn vị *");

        txtTenDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(97, 67, 67));
        jLabel40.setText("Địa chỉ *");

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(97, 67, 67));
        jLabel41.setText("Số điện thoại * ");

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(97, 67, 67));
        jLabel42.setText("Email * ");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(97, 67, 67));
        jLabel43.setText("Website *");

        txtWebsite.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnXoa.setBackground(new java.awt.Color(191, 158, 117));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(191, 158, 117));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/update.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(191, 158, 117));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(191, 158, 117));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/lammoi.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        tblDonVi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn vị", "Tên đơn vị", "Địa chỉ", "Số điện thoại", "Email", "Website"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDonVi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonViMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDonVi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if (txtTimKiem.getText().isEmpty()) {
            fillAllTable();
            this.clearForm();
            this.row = -1;
            updateStatus();
        } else {
            timKiem();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (row != -1) {
            row = -1;
            rowUpdate = 1;
            updateStatus();
            btnThem.setText("Lưu");
            txtMaDV.setEditable(false);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String src = evt.getActionCommand();
        if (src.equalsIgnoreCase("Thêm")) {
            insert();
        } else if (src.equalsIgnoreCase("Lưu")) {
            update();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tblDonViMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonViMouseClicked
        if (evt.getClickCount() == 1) {
            this.row = tblDonVi.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblDonViMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDonVi;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtWebsite;
    // End of variables declaration//GEN-END:variables
    DonViDao dvdao = new DonViDao();
    int row = -1;
    int rowUpdate = -1;
    private void init() {
        this.fillAllTable();
        this.row = -1;
        this.rowUpdate = -1;
        this.updateStatus();

        setBorderInput();
        focusInput();
    }

    void insert() {
        if (checkValidateForm()) {
            DonVi nv = getForm();
            try {
                dvdao.insert(nv);
                this.fillAllTable();
                this.clearForm();
                MsgBox.alert(this, "Thêm mới thành công!", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                //throw new RuntimeException(e);
                MsgBox.alert(this, "Thêm mới thất bại", JOptionPane.WARNING_MESSAGE);
            }

        }

    }

    void update() {
        if (checkValidateForm()) {
            DonVi dv = getForm();
            try {
                dvdao.update(dv);
                this.fillAllTable();
                MsgBox.alert(this, "Cập nhật thành công!", JOptionPane.INFORMATION_MESSAGE);
                this.clearForm();
            } catch (Exception e) {
                //throw new RuntimeException(e);
                MsgBox.alert(this, "Cập nhật thất bại", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa đơn vị!", JOptionPane.WARNING_MESSAGE);
        } else if (MsgBox.confirm(this, "Bạn thực sự muốn xóa đơn vị này?")) {
            String maDV = txtMaDV.getText();
            if(maDV.equals("DV01")){ 
                MsgBox.alert(this, "Bạn không có quyền xóa đơn vị! "+maDV, JOptionPane.WARNING_MESSAGE);
            } else { 
                try {
                dvdao.delete(maDV);
                this.fillAllTable();
                this.clearForm();
                MsgBox.alert(this, "Xóa thành công", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                //throw new RuntimeException(e);
                MsgBox.alert(this, "Xóa thất bại", JOptionPane.WARNING_MESSAGE);
            }
            }    
        }
    }

    void clearForm() {
        DonVi dv = new DonVi();
        this.setForm(dv);
        this.row = -1;
        this.rowUpdate = -1;
        this.updateStatus();
        tblDonVi.clearSelection();

    }

    void edit() {
        String madv = (String) tblDonVi.getValueAt(this.row, 0);
        DonVi dv = dvdao.selectById(madv);
        this.setForm(dv);
        this.updateStatus();
    }

    void fillAllTable() {
        DefaultTableModel model = (DefaultTableModel) tblDonVi.getModel();
        model.setRowCount(0);
        try {
            String keyWord = txtTimKiem.getText();
            List<DonVi> list = dvdao.selectAll();
            for (DonVi dv : list) {
                Object[] row = {dv.getMaDV(), dv.getTenDV(), dv.getDiaChi(), dv.getSDT(), dv.getEmail(), dv.getWebsite()};
                model.addRow(row);
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
            // MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void filltimkiemtable() {
        DefaultTableModel model = (DefaultTableModel) tblDonVi.getModel();
        model.setRowCount(0);
        try {
            String keyWord = txtTimKiem.getText();
            List<DonVi> list = dvdao.selectByKeyWord(keyWord);
            if (list.isEmpty()) {
                MsgBox.alert(this, "Không có đơn vị nào!", JOptionPane.WARNING_MESSAGE);
            } else {
                for (DonVi dv : list) {
                    Object[] row = {dv.getMaDV(), dv.getTenDV(), dv.getDiaChi(), dv.getSDT(), dv.getEmail(), dv.getWebsite()};
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
            // MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private String layMaDV(String id) {
        List<DonVi> list = dvdao.selectAll();
        String ma = id;
        if (list.isEmpty()) {
            ma = ma + "01";
        } else {
            String maBCuoiList = list.get(list.size() - 1).getMaDV();
            int sauMaDV = Integer.valueOf(maBCuoiList.substring(2, maBCuoiList.length())) + 1;
            if (sauMaDV < 10) {
                ma = ma + "0" + sauMaDV;
            } else {
                ma = ma + sauMaDV;
            }
        }
        return ma;
    }

    void setForm(DonVi dv) {
        txtMaDV.setText(dv.getMaDV());
        txtTenDV.setText(dv.getTenDV());
        txtDiaChi.setText(dv.getDiaChi());
        txtSDT.setText(dv.getSDT());
        txtEmail.setText(dv.getEmail());
        txtWebsite.setText(dv.getWebsite());

    }

    DonVi getForm() {
        DonVi dv = new DonVi();
        if(rowUpdate == -1){
            // Insert
           dv.setMaDV(layMaDV("DV"));
        } else {
            // Update
            dv.setMaDV(txtMaDV.getText());
        }
        dv.setTenDV(txtTenDV.getText());
        dv.setDiaChi(txtDiaChi.getText());
        dv.setSDT(txtSDT.getText());
        dv.setEmail(txtEmail.getText());
        dv.setWebsite(txtWebsite.getText());
        return dv;
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        //Trạng thái form
        txtMaDV.setEditable(false);
        txtTenDV.setEditable(!edit);
        txtDiaChi.setEditable(!edit);
        txtSDT.setEditable(!edit);
        txtEmail.setEditable(!edit);
        txtWebsite.setEditable(!edit);

        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        btnThem.setText("Thêm");

    }

    boolean checkValidateForm() {
        if (txtTenDV.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập tên đơn vị!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txtDiaChi.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập địa chỉ!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txtSDT.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập số điện thoại!", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            try {
                long sdt = Long.parseLong(txtSDT.getText());
                if (sdt < 0) {
                    MsgBox.alert(this, "Số điện thoại không được là số âm!", JOptionPane.WARNING_MESSAGE);
                    return false;
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Số điện thoại phải là số!", JOptionPane.WARNING_MESSAGE);
                return false;
            }
            String sdt10so = "\\d{10}";
            if (!txtSDT.getText().matches(sdt10so)) {
                MsgBox.alert(this, "Số điện thoại phải là 10 số!", JOptionPane.WARNING_MESSAGE);
                return false;
            }

            String patternSDT = "^(0[3-9])\\d{8}$";
            if (!txtSDT.getText().matches(patternSDT)) {
                MsgBox.alert(this, "Số điện thoại không đúng định dạng!", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        if (txtEmail.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập email!", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            String patternEmail = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+(\\.[A-Za-z]{2,}){1,2}$";
            if (!txtEmail.getText().matches(patternEmail)) {
                MsgBox.alert(this, "Email! không hợp lệ", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        if (txtWebsite.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập website!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void timKiem() {
        this.filltimkiemtable();
        this.clearForm();
        this.row = -1;
        updateStatus();
    }

    private void focusInput() {
        Border borderNhanVao = BorderFactory.createLineBorder(new Color(227, 188, 140), 10, true);
        Border borderKhongNhan = BorderFactory.createLineBorder(new Color(255, 255, 255), 10, true);
        txtTenDV.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtTenDV.setBackground(new Color(227, 188, 140));
                txtTenDV.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtTenDV.setBackground(new Color(255, 255, 255));
                txtTenDV.setBorder(borderKhongNhan);
            }
        });
        txtDiaChi.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtDiaChi.setBackground(new Color(227, 188, 140));
                txtDiaChi.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtDiaChi.setBackground(new Color(255, 255, 255));
                txtDiaChi.setBorder(borderKhongNhan);
            }
        });
        txtSDT.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtSDT.setBackground(new Color(227, 188, 140));
                txtSDT.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtSDT.setBackground(new Color(255, 255, 255));
                txtSDT.setBorder(borderKhongNhan);
            }
        });
        txtEmail.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtEmail.setBackground(new Color(227, 188, 140));
                txtEmail.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtEmail.setBackground(new Color(255, 255, 255));
                txtEmail.setBorder(borderKhongNhan);
            }
        });
        txtWebsite.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtWebsite.setBackground(new Color(227, 188, 140));
                txtWebsite.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtWebsite.setBackground(new Color(255, 255, 255));
                txtWebsite.setBorder(borderKhongNhan);
            }
        });
        txtTimKiem.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtTimKiem.setBackground(new Color(227, 188, 140));
                txtTimKiem.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtTimKiem.setBackground(new Color(255, 255, 255));
                txtTimKiem.setBorder(borderKhongNhan);
            }
        });
    }

    private void setBorderInput() {
        Border border = BorderFactory.createLineBorder(new Color(255, 255, 255), 10, true);
        txtTenDV.setBorder(border);
        txtDiaChi.setBorder(border);
        txtSDT.setBorder(border);
        txtEmail.setBorder(border);
        txtWebsite.setBorder(border);
        txtTimKiem.setBorder(border);

    }

}
