/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.form;

import com.cafe.dao.ChiTietHoaDonDAO;
import com.cafe.dao.HoaDonDAO;
import com.cafe.dao.NhanVienDAO;
import com.cafe.dao.SanPhamDAO;
import com.cafe.dao.ThongKeBaoCaoDAO;
import com.cafe.model.ChiTietHoaDon;
import com.cafe.model.HoaDon;
import com.cafe.model.SanPham;
import com.cafe.model.ThongKeBaoCao;
import com.cafe.utils.MsgBox;
import com.cafe.utils.XDate;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ACER
 */
public class ThongKeBaoCaoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeBaoCaoJPanel
     */
    public ThongKeBaoCaoJPanel() {
        initComponents();
        init();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        cboTheoSanPham = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        btnXuatFile = new javax.swing.JButton();
        btnXemThongKe = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDoanhThuSP = new javax.swing.JTable();
        dateTuNgay = new com.toedter.calendar.JDateChooser();
        dateDenNgay = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(230, 213, 193));

        jPanel7.setBackground(new java.awt.Color(230, 213, 193));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(97, 67, 67));
        jLabel52.setText("Từ");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(97, 67, 67));
        jLabel56.setText("Đến");

        cboTheoSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboTheoSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTheoSanPhamActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(97, 67, 67));
        jLabel58.setText("Theo Sản Phẩm");

        btnXuatFile.setBackground(new java.awt.Color(191, 158, 117));
        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnXuatFile.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/xuatfile.png"))); // NOI18N
        btnXuatFile.setText("Xuất file Excel");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });

        btnXemThongKe.setBackground(new java.awt.Color(191, 158, 117));
        btnXemThongKe.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnXemThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnXemThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/thongke.png"))); // NOI18N
        btnXemThongKe.setText("Xem thống kê");
        btnXemThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemThongKeActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(97, 67, 67));
        jLabel51.setText("DANH SÁCH NHÂN VIÊN");

        jLabel33.setBackground(new java.awt.Color(97, 67, 67));
        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(97, 67, 67));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Thống Kê Và Báo Cáo");

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Đơn Vị", "Tên Đơn Vị", "Tổng Doanh Thu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThongKeMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblThongKe);

        jTabbedPane1.addTab("Thống Kê Theo Đơn Vị", jScrollPane4);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Đơn Vị", "Mã Nhân Viên", "Tên Nhân Viên", "Doanh Số"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jTabbedPane1.addTab("Thống Kê Theo Nhân Viên", jScrollPane1);

        tblDoanhThuSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Loại Sản Phẩm", "Đơn Giá", "Số Lượng Bán", "Tổng Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDoanhThuSP);

        jTabbedPane1.addTab("Thống Kê Theo Sản Phẩm", jScrollPane2);

        dateTuNgay.setDateFormatString("yyyy-MM-dd");

        dateDenNgay.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXemThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateTuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXuatFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateDenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(cboTheoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel56)
                    .addComponent(jLabel58)
                    .addComponent(cboTheoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        xuatFile();
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnXemThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemThongKeActionPerformed
        if (checkValidateForm()) {
            xemThongKe();
        }
    }//GEN-LAST:event_btnXemThongKeActionPerformed

    private void cboTheoSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTheoSanPhamActionPerformed
        String loai = (String) cboTheoSanPham.getSelectedItem();
        fillToThongKeTable();
        if (loai.equals("Tất cả")) {
            fillHoaDonToTable();
            fillDoanhThuSPToTable();
        } else {
//            fillHoaDonToTableTheoLoai();
            fillDoanhThuSPToTableTheoLoai();
        }
    }//GEN-LAST:event_cboTheoSanPhamActionPerformed

    private void tblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeMouseClicked

    }//GEN-LAST:event_tblThongKeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXemThongKe;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JComboBox<String> cboTheoSanPham;
    private com.toedter.calendar.JDateChooser dateDenNgay;
    private com.toedter.calendar.JDateChooser dateTuNgay;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDoanhThuSP;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables

    //
    ThongKeBaoCaoDAO thongKeDAO = new ThongKeBaoCaoDAO();
    SanPhamDAO spdao = new SanPhamDAO();
    HoaDonDAO hddao = new HoaDonDAO();
    ThongKeBaoCao tK = new ThongKeBaoCao();
    ChiTietHoaDonDAO cthddao = new ChiTietHoaDonDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    ArrayList<ThongKeBaoCao> thongKe = new ArrayList();
    int row = -1;

//    int countXemHD = -1;
    private void init() {
        fillComboBoxTheoLoai();
        this.fillToThongKeTable();
        this.fillHoaDonToTable();
        fillDoanhThuSPToTable();
        this.row = -1;
    }

    public void fillHoaDonToTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        List<Object[]> list = nvdao.getNhanVien();
        for (Object[] nv : list) {
            model.addRow(nv);
        }
    }

//    public void fillHoaDonToTableTheoLoai() {
//        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
//        model.setRowCount(0);
//        List<SanPham> splist = spdao.selectByKeyWord((String) cboTheoSanPham.getSelectedItem());
//        for (SanPham sanPham : splist) {
//            List<HoaDon> list = hddao.selectAll();
//            for (HoaDon hd : list) {
//                List<ChiTietHoaDon> listcthd = cthddao.selectByMaHD(hd.getMaHD());
//                for (ChiTietHoaDon chiTietHoaDon : listcthd) {
//                    if (chiTietHoaDon.getMaSP().equals(sanPham.getMaSP())) {
//                        model.addRow(new Object[]{hd.getMaHD(), hd.getMaBan(), hd.getNgayDatBan(), hd.getThoiGianTaoHD(), hd.getNgayThanhToan(),
//                            hd.getThoiGianThanhToan(), hd.getMaNV(), hd.getTongTien(), hd.isTrangThai() ? "Đã Thanh Toán" : "Chưa Thanh Toán"});
//                    }
//                }
//
//            }
//        }
//
//    }

    public void fillDoanhThuSPToTable() {
        DefaultTableModel model = (DefaultTableModel) tblDoanhThuSP.getModel();
        model.setRowCount(0);
        List<Object[]> list = spdao.getDoanhThuSP();
        for (Object[] sp : list) {
//            Object[] row = {sp.getMaSP(),sp.getTenSP(),sp.getLoaiSP(),sp.getGia(),sp.getSoLuong(),
//                       sp.getTongTien()};
            model.addRow(sp);
        }

    }

    public void fillDoanhThuSPToTableTheoLoai() {
        String loai = (String) cboTheoSanPham.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblDoanhThuSP.getModel();
        model.setRowCount(0);
        List<Object[]> list = spdao.getDoanhThuSPTheoLoai(loai);
        for (Object[] sp : list) {
//            Object[] row = {sp.getMaSP(),sp.getTenSP(),sp.getLoaiSP(),sp.getGia(),sp.getSoLuong(),
//                       sp.getTongTien()};
            model.addRow(sp);
            tblDoanhThuSP.setModel(model);
        }

    }

    public void fillToThongKeTable() {
        String loaiSP = (String) cboTheoSanPham.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) tblThongKe.getModel();
        model.setRowCount(0);
        try {
            List<Object[]> list = thongKeDAO.getThongKeDonVi();
            for (Object[] thongKe : list) {
                model.addRow(thongKe);
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }

    private void fillComboBoxTheoLoai() {
        List<SanPham> list = spdao.selectLayLoaiSP();
        cboTheoSanPham.addItem("Tất cả");
        for (SanPham sp : list) {
            cboTheoSanPham.addItem(sp.getLoaiSP());
        }
    }

    void xemThongKe() {
        DefaultTableModel modelThongKe = (DefaultTableModel) tblThongKe.getModel();
        DefaultTableModel modelHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        DefaultTableModel modelSanPham = (DefaultTableModel) tblDoanhThuSP.getModel();

        modelThongKe.setRowCount(0);
        modelHoaDon.setRowCount(0);
        modelSanPham.setRowCount(0);

        try {
            String tuNgay = XDate.toString(dateTuNgay.getDate(), "yyyy-MM-dd");
            Date tuNgay2 = XDate.toDate(tuNgay, "yyyy-MM-dd");
            String denNgay = XDate.toString(dateDenNgay.getDate(), "yyyy-MM-dd");
            Date denNgay2 = XDate.toDate(denNgay, "yyyy-MM-dd");

            List<Object[]> listThongKe = thongKeDAO.getThongKe(tuNgay2, denNgay2);

            if (listThongKe.isEmpty()) {
                MsgBox.alert(this, "Không có thống kê doanh thu nào từ " + tuNgay + " -> " + denNgay, JOptionPane.WARNING_MESSAGE);
            } else {
                for (Object[] thongKe : listThongKe) {
                   modelThongKe.addRow(new Object[]{thongKe[0], thongKe[1], thongKe[2]});
                }
            }

                        NhanVienDAO nv = new NhanVienDAO();
            List<Object[]> listNhanVien = nv.getNhanVienNgay(tuNgay2, denNgay2);
            if (listNhanVien.isEmpty()) {
                MsgBox.alert(this, "Không có danh sách hóa đơn nào từ " + tuNgay + " -> " + denNgay, JOptionPane.WARNING_MESSAGE);
            } else {
                for (Object[] nhanVien : listNhanVien) {
                    modelHoaDon.addRow(new Object[]{nhanVien[0], nhanVien[1], nhanVien[2], nhanVien[3]});

                }
            }
             List<Object[]> listSanPham = spdao.getDoanhThuSPNgay(tuNgay2, denNgay2);
            if (listSanPham.isEmpty()) {
                MsgBox.alert(this, "Không có danh sách sản phẩm nào từ " + tuNgay + " -> " + denNgay, JOptionPane.WARNING_MESSAGE);
            } else {
                for (Object[] sanPham : listSanPham) {
                    modelSanPham.addRow(new Object[]{sanPham[0], sanPham[1], sanPham[2], sanPham[3], sanPham[4], sanPham[5]});
                }
            }

        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    boolean checkValidateForm() {
        if (dateTuNgay.getDate() == null) {
            MsgBox.alert(this, "Vui lòng chọn từ ngày!", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        Date now = new Date();
        String ngay = XDate.toString(dateTuNgay.getDate(), "yyyy-MM-dd");
        Date tuNgaylan2 = XDate.toDate(ngay, "yyyy-MM-dd");

        if (tuNgaylan2.after(now)) {
            MsgBox.alert(this, "Từ ngày phải trước ngày hiện tại", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (dateDenNgay.getDate() == null) {
            MsgBox.alert(this, "Vui lòng chọn đến ngày!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        String denNgay = XDate.toString(dateDenNgay.getDate(), "yyyy-MM-dd");
        Date denNgaylan2 = XDate.toDate(denNgay, "yyyy-MM-dd");

        if (denNgaylan2.after(now)) {

            MsgBox.alert(this, "Đến ngày phải trước ngày hiện tại", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tuNgaylan2.after(denNgaylan2)) {
            MsgBox.alert(this, "Đến ngày phải sau từ ngày", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    public void xuatFile() {
       try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheetThongKe = workbook.createSheet("Thống Kê Theo Đơn Vị");
            XSSFSheet sheetHoaDon = workbook.createSheet("Thống Kê Theo Nhân Viên");
            XSSFSheet sheetSanPham = workbook.createSheet("Thống Kê Theo Sản Phẩm");

            XSSFRow row = null;
            Cell cell = null;
            row = sheetThongKe.createRow(1);

            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã Đơn Vị");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Tên Đơn Vị");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Tổng Doanh Thu");

            //nhan vien
            row = sheetHoaDon.createRow(1);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã Đơn Vị");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Nhân Viên");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Tên Nhân Viên");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Doanh Số");

            // san pham
            row = sheetSanPham.createRow(1);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã Sản Phẩm");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Tên Sản Phẩm");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Loại");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Đơn Giá");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Số Lượng Bán");

            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Tổng Tiền");
            //
            try {
                for (int i = 0; i < tblThongKe.getRowCount(); i++) {
                    row = sheetThongKe.createRow(2 + i);

                    cell = row.createCell(0, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblThongKe.getValueAt(i, 0)));

                    cell = row.createCell(1, CellType.STRING);
                    cell.setCellValue((String) tblThongKe.getValueAt(i, 1));

                    cell = row.createCell(2, CellType.STRING);
                    cell.setCellValue((Double) tblThongKe.getValueAt(i, 2));
                }

                for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
                    row = sheetHoaDon.createRow(2 + i);

                    cell = row.createCell(0, CellType.STRING);
                    cell.setCellValue(String.valueOf( tblHoaDon.getValueAt(i, 0)));

                    cell = row.createCell(1, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblHoaDon.getValueAt(i, 1)));

                    cell = row.createCell(2, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblHoaDon.getValueAt(i, 2)));

                    cell = row.createCell(3, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblHoaDon.getValueAt(i, 3)));

                }
                for (int i = 0; i < tblDoanhThuSP.getRowCount(); i++) {

                    row = sheetSanPham.createRow(2 + i);

                    cell = row.createCell(0, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblDoanhThuSP.getValueAt(i, 0)));

                    cell = row.createCell(1, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblDoanhThuSP.getValueAt(i, 1)));

                    cell = row.createCell(2, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblDoanhThuSP.getValueAt(i, 2)));

                    cell = row.createCell(3, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblDoanhThuSP.getValueAt(i, 3)));

                    cell = row.createCell(4, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblDoanhThuSP.getValueAt(i, 4)));

                    cell = row.createCell(5, CellType.STRING);
                    cell.setCellValue(String.valueOf(tblDoanhThuSP.getValueAt(i, 5)));

                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

            File f = new File("C:\\Users\\NGHIA\\Documents\\HOC KY 4\\Du an 1 - PRO1041\\QuanLyCaFe\\BrotherCafe\\src\\com\\cafe\\connect\\thongke.xlsx");
            try {
                FileOutputStream fis = new FileOutputStream(f);
                workbook.write(fis);
                fis.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();

            } catch (IOException e) {
                e.printStackTrace();
            }
            MsgBox.alert(this, "Xuất file thành công", JOptionPane.WARNING_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi xuất file", JOptionPane.INFORMATION_MESSAGE);
        }
    }


}
