/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cafe.form;

import com.cafe.dao.BanDAO;
import com.cafe.dao.ChiTietHoaDonDAO;
import com.cafe.dao.HoaDonDAO;
import com.cafe.dao.KhachHangDAO;
import com.cafe.dao.KhuVucDAO;
import com.cafe.dao.SanPhamDAO;
import com.cafe.model.Ban;
import com.cafe.model.ChiTietHoaDon;
import com.cafe.model.HoaDon;
import com.cafe.model.KhachHang;
import com.cafe.model.KhuVuc;
import com.cafe.model.NhanVien;
import com.cafe.model.SanPham;
import com.cafe.utils.Auth;
import com.cafe.utils.MsgBox;
import com.cafe.utils.XDate;
import com.cafe.utils.XImage;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NGHIA
 */
public class TrangChuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrangChu
     */
    public TrangChuJPanel() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuBan = new javax.swing.JPopupMenu();
        mnChuyenBan = new javax.swing.JMenuItem();
        mnGopBan = new javax.swing.JMenuItem();
        mnDatBan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnThanhToan = new javax.swing.JMenuItem();
        timeGioDen = new com.raven.swing.TimePicker();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblGioiDen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblBan = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        btnLichSuHoaDon = new javax.swing.JButton();
        pnCenter = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnChuyenBan = new javax.swing.JButton();
        btnGopBan = new javax.swing.JButton();
        btnDatBan = new javax.swing.JButton();

        mnChuyenBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnChuyenBan.setForeground(new java.awt.Color(0, 0, 0));
        mnChuyenBan.setText("Chuyển bàn");
        mnChuyenBan.setToolTipText("");
        mnChuyenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnChuyenBanActionPerformed(evt);
            }
        });
        popupMenuBan.add(mnChuyenBan);

        mnGopBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnGopBan.setForeground(new java.awt.Color(0, 0, 0));
        mnGopBan.setText("Gộp bàn");
        mnGopBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnGopBanActionPerformed(evt);
            }
        });
        popupMenuBan.add(mnGopBan);

        mnDatBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnDatBan.setForeground(new java.awt.Color(0, 0, 0));
        mnDatBan.setText("Đặt bàn");
        mnDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDatBanActionPerformed(evt);
            }
        });
        popupMenuBan.add(mnDatBan);
        popupMenuBan.add(jSeparator1);

        mnThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnThanhToan.setForeground(new java.awt.Color(0, 0, 0));
        mnThanhToan.setText("Thanh toán");
        mnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThanhToanActionPerformed(evt);
            }
        });
        popupMenuBan.add(mnThanhToan);

        timeGioDen.set24hourMode(true);

        setBackground(new java.awt.Color(230, 213, 193));
        setPreferredSize(new java.awt.Dimension(1536, 864));
        setLayout(new java.awt.BorderLayout(10, 0));

        jPanel4.setBackground(new java.awt.Color(191, 158, 117));
        jPanel4.setPreferredSize(new java.awt.Dimension(390, 864));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Giá", "Tổng tiền SP", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setFocusable(false);
        tblHoaDon.setOpaque(false);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Giờ đến:");

        lblGioiDen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tổng tiền:");

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGioiDen, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGioiDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(165, 138, 104));

        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/list.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOrder.setPreferredSize(new java.awt.Dimension(100, 23));
        btnOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/cashregister.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThanhToan.setPreferredSize(new java.awt.Dimension(88, 23));
        btnThanhToan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bàn:");
        jLabel3.setPreferredSize(new java.awt.Dimension(38, 35));

        lblBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBan.setForeground(new java.awt.Color(220, 0, 21));
        lblBan.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Trạng thái:");

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai.setForeground(new java.awt.Color(0, 0, 255));
        lblTrangThai.setPreferredSize(new java.awt.Dimension(0, 35));

        btnLichSuHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btnLichSuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLichSuHoaDon.setForeground(new java.awt.Color(97, 67, 67));
        btnLichSuHoaDon.setText("Lịch sử hóa đơn");
        btnLichSuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichSuHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnLichSuHoaDon)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLichSuHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel4, java.awt.BorderLayout.LINE_END);

        pnCenter.setBackground(new java.awt.Color(230, 213, 193));
        pnCenter.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(217, 189, 156));
        jPanel6.setPreferredSize(new java.awt.Dimension(730, 80));

        btnChuyenBan.setBackground(new java.awt.Color(255, 255, 255));
        btnChuyenBan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnChuyenBan.setForeground(new java.awt.Color(97, 67, 67));
        btnChuyenBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/chuyenban.png"))); // NOI18N
        btnChuyenBan.setText("Chuyển bàn");
        btnChuyenBan.setPreferredSize(new java.awt.Dimension(180, 50));
        btnChuyenBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenBanActionPerformed(evt);
            }
        });

        btnGopBan.setBackground(new java.awt.Color(255, 255, 255));
        btnGopBan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnGopBan.setForeground(new java.awt.Color(97, 67, 67));
        btnGopBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/gopban.png"))); // NOI18N
        btnGopBan.setText("Gộp bàn");
        btnGopBan.setPreferredSize(new java.awt.Dimension(180, 50));
        btnGopBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGopBanActionPerformed(evt);
            }
        });

        btnDatBan.setBackground(new java.awt.Color(255, 255, 255));
        btnDatBan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnDatBan.setForeground(new java.awt.Color(97, 67, 67));
        btnDatBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cafe/icon/datban.png"))); // NOI18N
        btnDatBan.setText("Đặt bàn");
        btnDatBan.setPreferredSize(new java.awt.Dimension(180, 50));
        btnDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatBanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGopBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGopBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnCenter.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        add(pnCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        OrDerSP();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        thanhToan();
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenBanActionPerformed
        chonChuyenBan();
    }//GEN-LAST:event_btnChuyenBanActionPerformed

    private void btnGopBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGopBanActionPerformed
        chonGopBan();
    }//GEN-LAST:event_btnGopBanActionPerformed

    private void btnDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatBanActionPerformed
        chonDatBan();
    }//GEN-LAST:event_btnDatBanActionPerformed

    private void btnLichSuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuHoaDonActionPerformed
        new LichSuHoaDonJDialog(null, true).setVisible(true);
    }//GEN-LAST:event_btnLichSuHoaDonActionPerformed

    private void mnChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnChuyenBanActionPerformed
        chonChuyenBan();
    }//GEN-LAST:event_mnChuyenBanActionPerformed

    private void mnGopBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnGopBanActionPerformed
        chonGopBan();
    }//GEN-LAST:event_mnGopBanActionPerformed

    private void mnDatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDatBanActionPerformed
        chonDatBan();
    }//GEN-LAST:event_mnDatBanActionPerformed

    private void mnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThanhToanActionPerformed
        thanhToan();
    }//GEN-LAST:event_mnThanhToanActionPerformed

    private void tblHoaDonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseReleased
        if (evt.isPopupTrigger()) {
            xoaSPtrongCTHD();
        }
        if (evt.getClickCount() == 2) {
            intOkSuaSL = tblHoaDon.getSelectedRow();
            int sl = (int) tblHoaDon.getValueAt(intOkSuaSL, 2);
            String ghiChu = (String) tblHoaDon.getValueAt(intOkSuaSL, 5);
            suaSLSPtrongCTHD(sl, ghiChu);
        }
    }//GEN-LAST:event_tblHoaDonMouseReleased
    private void btnOKSuaSoLuongActionPerformed(java.awt.event.ActionEvent evt) {
        okSuaSoLuongCTHD();
    }

    private void btnKhuVucActionPerformed(java.awt.event.ActionEvent evt) {
        String src = evt.getActionCommand();
        pn_MenuKV.setVisible(false);
        fillBan(src);
    }

    private void lblMenuSPMouseClicked(java.awt.event.MouseEvent evt) {
        String text = lblMenuSP.getText();
        int dau = text.indexOf(":");
        int cuoi = text.indexOf("<br>");
        tenSP = text.substring(dau + 10, cuoi);
        clickVaoSP();
    }
    int xBan = -1;
    int yBan = -1;

    private void lblBanTrongKhuVucMouseClicked(java.awt.event.MouseEvent evt) {
        String text = lblKhuVucBan.getText();
        int dau = text.indexOf(":");
        int cuoi = text.indexOf("<br>");
        tenBan = text.substring(dau + 10, cuoi);
        fillTable();
        clickBan();
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        pn_MenuKV.setVisible(false);
        KhuVuc kv = kvdao.selectById(b.getKhuVuc());
        fillBan(kv.getTenKV());
        if (b.getTrangThai().equals("Đã đặt")) {
            btnDatBan.setText("Hủy đặt bàn");
            mnDatBan.setText("Hủy đặt bàn");
        } else {
            btnDatBan.setText("Đặt bàn");
            mnDatBan.setText("Đặt bàn");
        }
        Point point = lblKhuVucBan.getLocation();
        xBan = point.x;
        yBan = point.y;

    }

    private void lblBanTrongKhuVucMouseReleased(java.awt.event.MouseEvent evt) {
        if (evt.isPopupTrigger()) {
            if (tenBan != null) {
                if (xBan != -1 && yBan != -1) {
                    Component p = evt.getComponent();
                    if (xBan == p.getX() && yBan == p.getY()) {
                        popupMenuBan.show(evt.getComponent(), evt.getX(), evt.getY());
                    }
                }
            }
        }
    }

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {
        dgChonSL.setVisible(false);
    }

    private void btnOKChonSoLuongActionPerformed(java.awt.event.ActionEvent evt) {
        if (checkValidateFormChonSL()) {
            thoiGianTT = -1;
            updateBanKhiOrderVaTT();
            OrderChonSL();
            fillTable();
            clickBan();
            dgChonSL.setVisible(false);
            checkTableRong = false;
        }

    }

    private void btnOkChuyenBanActionPerformed(java.awt.event.ActionEvent evt) {
        chuyenBanNhanOk();
        dgChuyenBan.setVisible(false);

    }

    private void btnOkGopBanActionPerformed(java.awt.event.ActionEvent evt) {
        gopBanNhanOK();
        dgGopBan.setVisible(false);
    }

    private void btnOkDatBanActionPerformed(java.awt.event.ActionEvent evt) {
        datBanOK();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenBan;
    private javax.swing.JButton btnDatBan;
    private javax.swing.JButton btnGopBan;
    private javax.swing.JButton btnLichSuHoaDon;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblBan;
    private javax.swing.JLabel lblGioiDen;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JMenuItem mnChuyenBan;
    private javax.swing.JMenuItem mnDatBan;
    private javax.swing.JMenuItem mnGopBan;
    private javax.swing.JMenuItem mnThanhToan;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPopupMenu popupMenuBan;
    private javax.swing.JTable tblHoaDon;
    private com.raven.swing.TimePicker timeGioDen;
    // End of variables declaration//GEN-END:variables
    private JPanel pn_MenuSP;
    private JPanel pn_Menu;
    private JPanel pn_MenuKV;
    private JPanel pn_KhuVuc;
    private JButton btnKhuVuc;
    private JLabel JlabelMenuSP;
    private JLabel JLabelKhuVuc;
    private JLabel lblMenuSP;
    private JLabel lblKhuVucBan;
    private JButton btnOkChonSoLuong;
    private JButton btnHuyChonSoLuong;
    private JDialog dgChonSL;
    private JTextField txtGhiChu;
    private JTextField txtSoLuong;
    private JDialog dgChuyenBan;
    private JComboBox cboChuyenBan;
    private JButton btnOkChuyenBan;
    private JButton btnHuyChuyenBan;
    private JDialog dgGopBan;
    private JComboBox cboGopBan;
    private JButton btnOkGopBan;
    private JButton btnHuyGopBan;
    private JDialog dgDatBan;
    private ButtonGroup btgGioiTinh;
    private JRadioButton rdoNam;
    private JRadioButton rdoNu;
    private JTextField txtTenKH;
    private JTextField txtSoDT;
    private JButton btnOkDatBan;
    private JButton btnHuyDatBan;
    private JDateChooser dateNgayDen;
    private JTextField txtGioiDen;
    private JButton btnChonGio;
    private JDialog dgSuaSL;
    private JTextField txtSuaGhiChu;
    private JTextField txtSuaSoLuong;
    private JButton btnOkSuaSoLuong;
    private JDialog dgBill;
    private JButton btnInBill;
    private JButton btbHuyInBill;
    private JEditorPane ed_Page;

    KhuVucDAO kvdao = new KhuVucDAO();
    SanPhamDAO spdao = new SanPhamDAO();
    BanDAO bdao = new BanDAO();
    HoaDonDAO hddao = new HoaDonDAO();
    ChiTietHoaDonDAO cthddao = new ChiTietHoaDonDAO();
    KhachHangDAO khdao = new KhachHangDAO();

    List<KhuVuc> listKV = kvdao.selectAll();
    List<SanPham> listSP = spdao.selectAll();
    List<Ban> listBan = bdao.selectAll();
    List<ChiTietHoaDon> listCTHD;

    List<JLabel> JlabelMenuSPs = new ArrayList<>();
    List<JLabel> JlabelKhuVucs = new ArrayList<>();
    int clickOrder = -1;
    int index;
    int thoiGianTT = -1;
    int setlblrong = -1;
    static String tenBan = null;
    String tenSP = null;
    int intOkSuaSL = -1;
    boolean checkFillDuoiTable = true;
    boolean checkTableRong = false;
    String maKH = null;
    String maKHCheck = "KH";

    private void init() {
        giaoDienChinh();
        datLaiBanKhiQuaGio();

    }

    public void giaoDienChinh() {
        pn_KhuVuc = new JPanel(null);
        pn_KhuVuc.setPreferredSize(new Dimension(getWidth(), 80));
        pn_KhuVuc.setBackground(new Color(217, 189, 156));

        //JScrollPane sp_KhuVuc = new JScrollPane(pn_KhuVuc, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        pn_Menu = new JPanel();
        pn_Menu.setSize(getWidth(), 764);
        pn_Menu.setBackground(new Color(230, 213, 193));

        pnCenter.add(pn_KhuVuc, BorderLayout.NORTH);

        pn_MenuSP = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 15));
        pn_MenuSP.setPreferredSize(new Dimension(getWidth(), 864));
        pn_MenuSP.setSize(getWidth(), 864);
        pn_MenuSP.setBackground(new Color(230, 213, 193));

        pnCenter.add(pn_MenuSP, BorderLayout.CENTER);
        pn_MenuSP.setVisible(false);

        pn_MenuKV = new JPanel(new FlowLayout(FlowLayout.LEADING, 10, 10));
        pn_MenuKV.setPreferredSize(new Dimension(200, 864));
        pn_MenuKV.setSize(200, 864);
        pn_MenuKV.setBackground(new Color(230, 213, 193));

        // Thêm button trên thanh khu vực
        int xKhuVuc = 15;
        int yKhuVuc = 15;
        for (KhuVuc kv : listKV) {
            if (kv.getMaDV().equals(Auth.user.getMaDV())) {
                btnKhuVuc = new JButton(kv.getTenKV());
                btnKhuVuc.setLocation(xKhuVuc, yKhuVuc);
                xKhuVuc = xKhuVuc + 145;
                btnKhuVuc.setPreferredSize(new Dimension(130, 50));
                btnKhuVuc.setSize(130, 50);
                btnKhuVuc.setBackground(new Color(255, 255, 255));
                btnKhuVuc.setForeground(new Color(97, 67, 67));
                btnKhuVuc.setFont(new Font("Segoe UI", Font.BOLD, 16));
                btnKhuVuc.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        btnKhuVucActionPerformed(e);
                    }
                });

                pn_KhuVuc.add(btnKhuVuc);
            }
        }

        DecimalFormat formatTienVND = new DecimalFormat("###,###.###");
        //Thêm sản phẩm trong giao diện chính
        for (SanPham sp : listSP) {
            ImageIcon imageIcon = XImage.read(sp.getHinhAnh());
            Image resizedImage = imageIcon.getImage().getScaledInstance(55, 55, Image.SCALE_SMOOTH);
            imageIcon.setImage(resizedImage);
            String ten = "<html><pstyle='text-align:center;'>" + sp.getTenSP() + " <br>" + formatTienVND.format(sp.getGia()) + " VNĐ" + "</p></html>";
            JlabelMenuSP = new JLabel(ten, imageIcon, JLabel.CENTER);
            JlabelMenuSP.setBackground(new Color(230, 213, 193));
            JlabelMenuSP.setOpaque(true);
            JlabelMenuSP.setPreferredSize(new Dimension(110, 100));
            JlabelMenuSP.setSize(110, 100);
            JlabelMenuSP.setHorizontalTextPosition(SwingConstants.CENTER);
            JlabelMenuSP.setHorizontalAlignment(SwingConstants.CENTER);
            JlabelMenuSP.setVerticalAlignment(SwingConstants.CENTER);
            JlabelMenuSP.setVerticalTextPosition(SwingConstants.BOTTOM);
            JlabelMenuSP.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lblMenuSP = (JLabel) evt.getSource();
                    index = JlabelMenuSPs.indexOf(lblMenuSP);
                    lblMenuSPMouseClicked(evt);
                }
            });
            pn_MenuSP.add(JlabelMenuSP);
        }
        String list = "";
        for (KhuVuc khuVuc : listKV) {
            if (khuVuc.getMaDV().equals(Auth.user.getMaDV())) {
                list = khuVuc.getTenKV();
                break;
            }
        }
        if (list != null) {
            pn_MenuKV.setVisible(false);
            fillBan(list);
        }

    }

    public void fillBan(String keyWord) {
        for (Ban b : listBan) {
            if (!b.getKhuVuc().equals(keyWord)) {
                pn_MenuKV.removeAll();
            }
        }
        List<KhuVuc> list = kvdao.selectByTenKVandDV(keyWord,Auth.user.getMaDV());
        List<Ban> listB = null;
        for (KhuVuc khuVuc : list) {
            listB = bdao.selectByMaKVTraVeBan(khuVuc.getMaKV());
        }
        if (listB != null) {
            for (Ban ban : listB) {
                ImageIcon imageIcon = null;
                if (ban.getTrangThai().equals("Trống")) {
                    imageIcon = XImage.read("table-trong.png");
                } else if (ban.getTrangThai().equalsIgnoreCase("Có khách")) {
                    imageIcon = XImage.read("table-cokhach.png");
                } else if (ban.getTrangThai().equals("Đã đặt")) {
                    imageIcon = XImage.read("table-dadat.png");
                }

                Image resizedImage = imageIcon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
                imageIcon.setImage(resizedImage);

                String ten = "<html> <p style='text-align:center;'>" + ban.getTenBan() + "<br>" + ban.getTrangThai() + "</p></html>";
                JLabelKhuVuc = new JLabel(ten, imageIcon, JLabel.CENTER);
                JLabelKhuVuc.setPreferredSize(new Dimension(120, 110));
                JLabelKhuVuc.setSize(120, 110);
                if (ban.getTenBan().equals(tenBan)) {
                    JLabelKhuVuc.setOpaque(true);
                    JLabelKhuVuc.setBackground(new Color(227, 188, 140));
                } else {
                    JLabelKhuVuc.setBackground(new Color(230, 213, 193));

                }
                JLabelKhuVuc.setFont(new Font("Roboto", Font.PLAIN, 13));
                JLabelKhuVuc.setHorizontalTextPosition(SwingConstants.CENTER);
                JLabelKhuVuc.setHorizontalAlignment(SwingConstants.CENTER);
                JLabelKhuVuc.setVerticalAlignment(SwingConstants.CENTER);
                JLabelKhuVuc.setVerticalTextPosition(SwingConstants.BOTTOM);
                JLabelKhuVuc.addMouseListener(new java.awt.event.MouseAdapter() {

                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        lblKhuVucBan = (JLabel) evt.getSource();
                        index = JlabelKhuVucs.indexOf(lblKhuVucBan);
                        lblBanTrongKhuVucMouseClicked(evt);
                    }

                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        lblBanTrongKhuVucMouseReleased(evt);
                    }
                });
                pn_MenuKV.add(popupMenuBan);
                pn_MenuKV.add(JLabelKhuVuc);
            }
            pnCenter.add(pn_MenuKV, BorderLayout.CENTER);
            pn_MenuKV.setVisible(true);
        }

    }

    public void clickBan() {
        DecimalFormat formatTienVND = new DecimalFormat("###,###.###");
        List<Ban> listBan = bdao.selectByTenBan(tenBan);
        String gioiDenFormatTime = null;
        for (Ban ban : listBan) {
            List<HoaDon> listHD = hddao.selectByMaBan(ban.getMaBan());
            if (setlblrong == 1) {
                lblBan.setText("");
                lblTrangThai.setText("");
            } else {
                lblBan.setText(ban.getTenBan());
                lblTrangThai.setText(ban.getTrangThai());
            }

            if (checkFillDuoiTable) {
                for (HoaDon hd : listHD) {
                    String gioDen;
                    if (hd.getNgayDatBan() != null) {
                        Date time = new Date();
                        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
                        gioDen = sdf.format(time);
                    } else {
                        gioDen = hd.getThoiGianTaoHD();

                    }
                    if (gioDen != null) {
                        gioiDenFormatTime = gioDen.substring(0, 8);
                    }
                    lblGioiDen.setText(gioiDenFormatTime);
                    lblTongTien.setText(formatTienVND.format(tongTienTuTable()));
                }
            } else {
                lblGioiDen.setText("");
                lblTongTien.setText("0 VNĐ");
            }
        }
    }

    public void fillTable() {
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        List<HoaDon> listHD = hddao.selectByMaBan(b.getMaBan());
        if (b.getTrangThai().equals("Có khách")) {
            for (HoaDon hd : listHD) {
                DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
                model.setRowCount(0);
                List<ChiTietHoaDon> cthdList = cthddao.selectByMaHD(hd.getMaHD());
                for (ChiTietHoaDon cthd : cthdList) {
                    SanPham sp = spdao.selectByMaSPTraVeTenSP(cthd.getMaSP());
                    model.addRow(new Object[]{cthd.getMaSP(), sp.getTenSP(), cthd.getSoLuong(), sp.getGia(), cthd.getSoLuong() * sp.getGia(), cthd.getGhiChu() == null ? "" : cthd.getGhiChu()});
                }
                checkFillDuoiTable = true;
            }
        } else if (b.getTrangThai().equals("Trống") || b.getTrangThai().equals("Đã đặt")) {
            DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
            model.setRowCount(0);
            checkFillDuoiTable = false;
        }
    }

    public Ban updateBanTrong() {
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        Ban bnew = new Ban();
        bnew.setMaBan(b.getMaBan());
        bnew.setKhuVuc(b.getKhuVuc());
        bnew.setTenBan(b.getTenBan());
        bnew.setTrangThai("Trống");
        return bnew;
    }

    public void OrDerSP() {
        if (tenBan == null) {
            MsgBox.alert(null, "Vui lòng chọn bàn", JOptionPane.WARNING_MESSAGE);
        } else {
            if (clickOrder == -1) {
                this.add(pn_MenuSP, BorderLayout.CENTER);
                pnCenter.setVisible(false);
                pn_MenuSP.setVisible(true);
                clickOrder = 1;
                Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
                if (b.getTrangThai().equals("Trống") || b.getTrangThai().equals("Đã đặt")) {
                    listCTHD = new ArrayList<>();
                } else {
                    listCTHD = cthddao.selectByMaBan(b.getMaBan());
                }

            } else if (clickOrder == 1) {
                pnCenter.setVisible(true);
                pn_MenuSP.setVisible(false);
                clickOrder = -1;
            }
        }
        if (tblHoaDon.getRowCount() == 0) {
            checkTableRong = true;
        } else {
            checkTableRong = false;
        }
    }

    private void clickVaoSP() {

        dgChonSL = new JDialog();
        dgChonSL.setUndecorated(true);
        dgChonSL.setPreferredSize(new Dimension(500, 250));
        dgChonSL.setSize(500, 250);

        JPanel pannel = new JPanel();
        pannel.setLayout(null);
        pannel.setPreferredSize(new Dimension(500, 250));
        pannel.setSize(500, 250);
        pannel.setBackground(Color.WHITE);

        JLabel jLabelSL = new JLabel("Số lượng:");
        jLabelSL.setPreferredSize(new Dimension(90, 35));
        jLabelSL.setSize(90, 40);
        jLabelSL.setFont(new Font("Roboto", Font.PLAIN, 20));
        jLabelSL.setForeground(new Color(0, 0, 0));
        jLabelSL.setLocation(30, 40);

        JLabel jLabelGC = new JLabel("Ghi chú:");
        jLabelGC.setPreferredSize(new Dimension(90, 35));
        jLabelGC.setSize(90, 40);
        jLabelGC.setFont(new Font("Roboto", Font.PLAIN, 20));
        jLabelGC.setForeground(new Color(0, 0, 0));
        jLabelGC.setLocation(30, 88);

        txtSoLuong = new JTextField();
        txtSoLuong.setPreferredSize(new Dimension(340, 40));
        txtSoLuong.setBackground(new Color(227, 188, 140));
        txtSoLuong.setOpaque(true);
        txtSoLuong.setFont(new Font("Roboto", Font.PLAIN, 20));
        txtSoLuong.setHorizontalAlignment(SwingConstants.RIGHT);
        Border border = BorderFactory.createLineBorder(new Color(227, 188, 140), 10, true);
        txtSoLuong.setSize(340, 40);
        txtSoLuong.setLocation(120, 40);
        txtSoLuong.setBorder(border);
        txtSoLuong.setText(1 + "");

        txtGhiChu = new JTextField();
        txtGhiChu.setPreferredSize(new Dimension(340, 40));
        txtGhiChu.setBackground(new Color(227, 188, 140));
        txtGhiChu.setFont(new Font("Roboto", Font.PLAIN, 20));
        txtGhiChu.setOpaque(true);
        txtGhiChu.setSize(340, 40);
        txtGhiChu.setLocation(120, 90);
        txtGhiChu.setBorder(border);

        btnOkChonSoLuong = new JButton("OK");
        btnOkChonSoLuong.setPreferredSize(new Dimension(150, 40));
        btnOkChonSoLuong.setSize(150, 40);
        btnOkChonSoLuong.setBackground(new Color(191, 158, 117));
        btnOkChonSoLuong.setFont(new Font("Roboto", Font.BOLD, 20));
        btnOkChonSoLuong.setForeground(new Color(255, 255, 255));
        btnOkChonSoLuong.setLocation(95, 160);
        btnOkChonSoLuong.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnOKChonSoLuongActionPerformed(e);
            }
        });

        btnHuyChonSoLuong = new JButton("Hủy");
        btnHuyChonSoLuong.setPreferredSize(new Dimension(150, 40));
        btnHuyChonSoLuong.setSize(150, 40);
        btnHuyChonSoLuong.setBackground(new Color(191, 158, 117));
        btnHuyChonSoLuong.setFont(new Font("Roboto", Font.BOLD, 20));
        btnHuyChonSoLuong.setForeground(new Color(255, 255, 255));
        btnHuyChonSoLuong.setLocation(255, 160);
        btnHuyChonSoLuong.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnHuyActionPerformed(e);
            }
        });

        pannel.add(jLabelSL);
        pannel.add(txtSoLuong);
        pannel.add(jLabelGC);
        pannel.add(txtGhiChu);
        pannel.add(btnOkChonSoLuong);
        pannel.add(btnHuyChonSoLuong);
        dgChonSL.add(pannel);
        dgChonSL.setVisible(true);
        dgChonSL.setLocationRelativeTo(null);
    }

    private void OrderChonSL() {
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        SanPham sp = spdao.selectByTenSPTraveMaSP(tenSP);
        if (b.getTrangThai().equals("Trống") || b.getTrangThai().equals("Có khách")) {
            HoaDon hdForm = getFormHD();

            HoaDon hdid = hddao.selectById(idHoaDon(tenBan));
            if (checkTableRong) {
                hddao.insert(hdForm);
            } else {
                HoaDon hdUpate = new HoaDon(idHoaDon(tenBan), hdid.getTongTien() + Double.valueOf(txtSoLuong.getText()) * sp.getGia());
                hddao.updateTongTien(hdUpate);
            }
            if (trungSPKhiOrder()) {
                int soluong = 0;
                List<ChiTietHoaDon> list = cthddao.selectByMaBan(b.getMaBan());
                for (ChiTietHoaDon cthdList : list) {
                    if (sp.getMaSP().equals(cthdList.getMaSP())) {
                        soluong = cthdList.getSoLuong() + Integer.valueOf(txtSoLuong.getText());
                        ChiTietHoaDon cthd = new ChiTietHoaDon(cthdList.getMaCTHD(), soluong, soluong * sp.getGia());
                        cthddao.updateSLSP(cthd);
                    }
                }
            } else {
                ChiTietHoaDon cthd = new ChiTietHoaDon();
                cthd.setMaHD(idHoaDon(tenBan));
                cthd.setMaSP(sp.getMaSP());
                cthd.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
                cthd.setGhiChu(txtGhiChu.getText());
                cthd.setTongTienSP(sp.getGia() * (Integer.valueOf(txtSoLuong.getText())));

                cthddao.insert(cthd);
            }

        } else if (b.getTrangThai().equals("Đã đặt")) {
            ChiTietHoaDon cthd = new ChiTietHoaDon();
            cthd.setMaHD(idHoaDon(tenBan));
            cthd.setMaSP(sp.getMaSP());
            cthd.setSoLuong(Integer.valueOf(txtSoLuong.getText()));
            cthd.setGhiChu(txtGhiChu.getText());
            cthd.setTongTienSP(sp.getGia() * (Integer.valueOf(txtSoLuong.getText())));

            cthddao.insert(cthd);

            HoaDon hdUpate = new HoaDon(idHoaDon(tenBan), tongTienTuTable());
            hddao.updateTongTien(hdUpate);
            btnDatBan.setText("Đặt bàn");
        }

    }

    private boolean trungSPKhiOrder() {
        SanPham sp = spdao.selectByTenSPTraveMaSP(tenSP);
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        List<ChiTietHoaDon> listcthd = cthddao.selectByMaBan(b.getMaBan());

        for (ChiTietHoaDon cthdList : listcthd) {
            if (sp.getMaSP().equals(cthdList.getMaSP())) {
                return true;
            }
        }
        return false;

    }

    private int idHoaDon(String keyWord) {
        Ban b = bdao.selectByTenBanTraVeBan(keyWord, Auth.user.getMaDV());
        List<HoaDon> hd = hddao.selectAll();
        for (HoaDon hoaDon : hd) {
            if (hoaDon.getMaBan().equals(b.getMaBan())) {
                if (!hoaDon.isTrangThai()) {
                    return hoaDon.getMaHD();
                }
            }
        }
        return -1;
    }

    private void updateBanKhiOrderVaTT() {
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        Ban bUp = new Ban();
        bUp.setMaBan(b.getMaBan());
        bUp.setTenBan(b.getTenBan());
        bUp.setKhuVuc(b.getKhuVuc());
        if (thoiGianTT == -1) {
            bUp.setTrangThai("Có khách");
        } else {
            bUp.setTrangThai("Trống");
        }
        if(b.getTrangThai().equals("Đã đặt")){
            checkTableRong = false;
        }
        bdao.update(bUp);
        pn_MenuKV.setVisible(false);
        KhuVuc kv = kvdao.selectById(b.getKhuVuc());
        fillBan(kv.getTenKV());
    }

    private HoaDon getFormHD() {
        HoaDon hd = new HoaDon();

        hd.setNgayDatBan(null);

        Date now = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngayTT = sdf.format(now);
        LocalTime time = LocalTime.now();
        if (thoiGianTT == -1) {
            hd.setNgayThanhToan(null);
            hd.setNgayThanhToan(null);
            hd.setTrangThai(false);
            hd.setThoiGianTaoHD(time.getHour() + ":" + time.getMinute() + ":" + time.getSecond());
            SanPham sp = spdao.selectByTenSPTraveMaSP(tenSP);
            hd.setTongTien(sp.getGia() * Integer.valueOf(txtSoLuong.getText()));
        } else if (thoiGianTT == 1) {
            hd.setMaHD(idHoaDon(tenBan));
            hd.setNgayThanhToan(XDate.toDate(ngayTT, "yyyy-MM-dd"));
            hd.setThoiGianThanhToan(time.getHour() + ":" + time.getMinute() + ":" + time.getSecond());
            hd.setTrangThai(true);
            hd.setThoiGianTaoHD(lblGioiDen.getText());
            hd.setTongTien(tongTienTuTable());

        }

        hd.setMaNV(Auth.user.getMaNV());
        //hd.setMaNV("nghiatv");
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        hd.setMaBan(b.getMaBan());
        if (b.getTrangThai().equals("Đã đặt")) {
            List<HoaDon> listhd = hddao.selectByMaBan(tenBan);
            for (HoaDon hoadon : listhd) {
                if (hoadon.getMaBan().equals(b.getMaBan()) && !hoadon.getNgayDatBan().equals("null")) {
                    hd.setMaKH(hoadon.getMaKH());
                }
            }
        } else {
            hd.setMaKH(null);
        }

        return hd;
    }

    Double tongTienTuTable() {
        double tt = 0;
        int size = tblHoaDon.getRowCount();
        for (int i = 0; i < size; i++) {
            tt += (Double) tblHoaDon.getValueAt(i, 4);
        }
        return tt;
    }

    private void thanhToan() {
        if (tenBan == null) {
            MsgBox.alert(this, "Vui lòng chọn bàn để thanh toán", JOptionPane.WARNING_MESSAGE);
        } else {
            Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
            if (b.getTrangThai().equals("Có khách")) {
                if (MsgBox.confirm(this, "Bạn có muốn thanh toán cho " + tenBan)) {
                    thoiGianTT = 1;
                    checkFillDuoiTable = false;
                    HoaDon hd = getFormHD();
                    hddao.update(hd);
                    updateBanKhiOrderVaTT();
                    setlblrong = 1;
                    clickBan();
                    fillTable();
                    pnCenter.setVisible(true);
                    pn_MenuSP.setVisible(false);
                    tenBan = null;
                    KhuVuc kv = kvdao.selectById(b.getKhuVuc());
                    fillBan(kv.getTenKV());
                    setlblrong = -1;
                    XuatHoaDon xhd = new XuatHoaDon();
                    xhd.XHDLayDuLieu(hd.getMaHD());
                    xhd.setVisible(true);
                }
            } else {
                MsgBox.alert(this, "Vui lòng chọn bàn có khách để thanh toán", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void chonChuyenBan() {
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        if (tenBan == null) {
            MsgBox.alert(null, "Vui lòng chọn bàn cần chuyển", JOptionPane.WARNING_MESSAGE);
        } else if (b.getTrangThai().equals("Trống") || b.getTrangThai().equals("Đã đặt")) {
            MsgBox.alert(null, "Vui lòng chọn bàn có khách để chuyển", JOptionPane.WARNING_MESSAGE);
        } else {
            dgChuyenBan = new JDialog();
            dgChuyenBan.setUndecorated(true);
            dgChuyenBan.setPreferredSize(new Dimension(500, 250));
            dgChuyenBan.setSize(500, 250);

            JPanel pannel = new JPanel();
            pannel.setLayout(null);
            pannel.setPreferredSize(new Dimension(500, 250));
            pannel.setSize(500, 250);
            pannel.setBackground(Color.WHITE);

            JLabel jLabelTen = new JLabel("Chọn bàn để chuyển");
            jLabelTen.setPreferredSize(new Dimension(500, 50));
            jLabelTen.setSize(500, 50);
            jLabelTen.setFont(new Font("Roboto", Font.PLAIN, 22));
            jLabelTen.setForeground(new Color(97, 67, 67));
            jLabelTen.setLocation(0, 10);
            jLabelTen.setHorizontalAlignment(SwingConstants.CENTER);
            jLabelTen.setVerticalAlignment(SwingConstants.CENTER);

            cboChuyenBan = new JComboBox();
            cboChuyenBan.setSize(300, 35);
            cboChuyenBan.setLocation(100, 70);

            for (Ban ban : listBan) {
                if (!tenBan.equals(ban.getTenBan()) && ban.getTrangThai().equals("Trống")) {
                    cboChuyenBan.addItem(ban.getTenBan());
                }
            }

            btnOkChuyenBan = new JButton("OK");
            btnOkChuyenBan.setPreferredSize(new Dimension(150, 40));
            btnOkChuyenBan.setSize(150, 40);
            btnOkChuyenBan.setBackground(new Color(191, 158, 117));
            btnOkChuyenBan.setFont(new Font("Roboto", Font.BOLD, 20));
            btnOkChuyenBan.setForeground(new Color(255, 255, 255));
            btnOkChuyenBan.setLocation(95, 160);
            btnOkChuyenBan.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnOkChuyenBanActionPerformed(e);
                }
            });

            btnHuyChuyenBan = new JButton("Hủy");
            btnHuyChuyenBan.setPreferredSize(new Dimension(150, 40));
            btnHuyChuyenBan.setSize(150, 40);
            btnHuyChuyenBan.setBackground(new Color(191, 158, 117));
            btnHuyChuyenBan.setFont(new Font("Roboto", Font.BOLD, 20));
            btnHuyChuyenBan.setForeground(new Color(255, 255, 255));
            btnHuyChuyenBan.setLocation(255, 160);
            btnHuyChuyenBan.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dgChuyenBan.setVisible(false);
                }
            });

            pannel.add(jLabelTen);
            pannel.add(cboChuyenBan);
            pannel.add(btnOkChuyenBan);
            pannel.add(btnHuyChuyenBan);
            dgChuyenBan.add(pannel);
            dgChuyenBan.setVisible(true);
            dgChuyenBan.setLocationRelativeTo(null);
        }
    }

    private void chuyenBanNhanOk() {
        String tenBanDuocChuyen = (String) cboChuyenBan.getSelectedItem();
        Ban b = updateBanTrong();
        bdao.update(b);

        Ban banDuocChuyen = bdao.selectByTenBanTraVeBan(tenBanDuocChuyen, Auth.user.getMaDV());
        banDuocChuyen.setMaBan(banDuocChuyen.getMaBan());
        banDuocChuyen.setTenBan(banDuocChuyen.getTenBan());
        banDuocChuyen.setKhuVuc(banDuocChuyen.getKhuVuc());
        banDuocChuyen.setTrangThai("Có khách");
        bdao.update(banDuocChuyen);

        HoaDon hd = new HoaDon(idHoaDon(tenBan), banDuocChuyen.getMaBan());
        hddao.updateMaBanCuaHD(hd);

        pn_MenuKV.setVisible(false);
        KhuVuc kv = kvdao.selectById(b.getKhuVuc());
        fillBan(kv.getTenKV());
        fillTable();
        clickBan();
    }

    private void chonGopBan() {
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        if (tenBan == null) {
            MsgBox.alert(null, "Vui lòng chọn bàn cần gộp", JOptionPane.WARNING_MESSAGE);
        } else if (b.getTrangThai().equals("Trống") || b.getTrangThai().equals("Đã đặt")) {
            MsgBox.alert(null, "Vui lòng chọn bàn có khách để gộp", JOptionPane.WARNING_MESSAGE);
        } else {
            dgGopBan = new JDialog();
            dgGopBan.setUndecorated(true);
            dgGopBan.setPreferredSize(new Dimension(500, 250));
            dgGopBan.setSize(500, 250);

            JPanel pannel = new JPanel();
            pannel.setLayout(null);
            pannel.setPreferredSize(new Dimension(500, 250));
            pannel.setSize(500, 250);
            pannel.setBackground(Color.WHITE);

            JLabel jLabelTen = new JLabel("Chọn bàn để Gộp");
            jLabelTen.setPreferredSize(new Dimension(500, 50));
            jLabelTen.setSize(500, 50);
            jLabelTen.setFont(new Font("Roboto", Font.PLAIN, 22));
            jLabelTen.setForeground(new Color(97, 67, 67));
            jLabelTen.setLocation(0, 10);
            jLabelTen.setHorizontalAlignment(SwingConstants.CENTER);
            jLabelTen.setVerticalAlignment(SwingConstants.CENTER);

            cboGopBan = new JComboBox();
            cboGopBan.setSize(300, 35);
            cboGopBan.setLocation(100, 70);

            listBan = bdao.selectAll();
            for (Ban ban : listBan) {
                if (!tenBan.equals(ban.getTenBan())) {
                    if (ban.getTrangThai().equals("Có khách")) {
                        cboGopBan.addItem(ban.getTenBan());
                    }
                }
            }

            btnOkGopBan = new JButton("OK");
            btnOkGopBan.setPreferredSize(new Dimension(150, 40));
            btnOkGopBan.setSize(150, 40);
            btnOkGopBan.setBackground(new Color(191, 158, 117));
            btnOkGopBan.setFont(new Font("Roboto", Font.BOLD, 20));
            btnOkGopBan.setForeground(new Color(255, 255, 255));
            btnOkGopBan.setLocation(95, 160);
            btnOkGopBan.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnOkGopBanActionPerformed(e);
                }
            });

            btnHuyGopBan = new JButton("Hủy");
            btnHuyGopBan.setPreferredSize(new Dimension(150, 40));
            btnHuyGopBan.setSize(150, 40);
            btnHuyGopBan.setBackground(new Color(191, 158, 117));
            btnHuyGopBan.setFont(new Font("Roboto", Font.BOLD, 20));
            btnHuyGopBan.setForeground(new Color(255, 255, 255));
            btnHuyGopBan.setLocation(255, 160);
            btnHuyGopBan.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dgGopBan.setVisible(false);
                }
            });

            pannel.add(jLabelTen);
            pannel.add(cboGopBan);
            pannel.add(btnOkGopBan);
            pannel.add(btnHuyGopBan);
            dgGopBan.add(pannel);
            dgGopBan.setVisible(true);
            dgGopBan.setLocationRelativeTo(null);
        }
    }

    private void gopBanNhanOK() {
        String tenBanDuocGop = (String) cboGopBan.getSelectedItem();

        Ban bGopChinh = bdao.selectByTenBanTraVeBan(tenBanDuocGop, Auth.user.getMaDV());
        Ban bGopPhu = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());

        List<ChiTietHoaDon> cthdGopPhu = cthddao.selectByMaBan(bGopPhu.getMaBan());
        int idhd = idHoaDon(bGopChinh.getTenBan());
        double tongtienHD = 0;
        for (ChiTietHoaDon cthdG : cthdGopPhu) {
            ChiTietHoaDon cthd = new ChiTietHoaDon();
            cthd.setMaCTHD(Integer.valueOf(cthdG.getMaCTHD()));
            cthd.setMaHD(idhd);
            cthd.setMaSP(cthdG.getMaSP());
            cthd.setSoLuong(cthdG.getSoLuong());
            cthd.setTongTienSP(cthdG.getTongTienSP());
            cthd.setGhiChu(cthdG.getGhiChu());
            cthddao.update(cthd);
        }
        List<ChiTietHoaDon> cthdGopChinh = cthddao.selectByMaBan(bGopChinh.getMaBan());
        for (ChiTietHoaDon cthdChinh : cthdGopChinh) {
            tongtienHD += cthdChinh.getTongTienSP();
        }

        Ban bUpdae = new Ban(bGopPhu.getMaBan(), bGopPhu.getTenBan(), "Trống", bGopPhu.getKhuVuc());
        bdao.update(bUpdae);

        HoaDon hđUpdate = new HoaDon(idHoaDon(bGopChinh.getTenBan()), tongtienHD);
        hddao.updateTongTien(hđUpdate);

        hddao.delete(idHoaDon(tenBan));

        pn_MenuKV.setVisible(false);
        KhuVuc kv = kvdao.selectById(bGopChinh.getKhuVuc());
        fillBan(kv.getTenKV());
        fillTable();
        clickBan();
    }

    private void chonDatBan() {
        if (btnDatBan.getText().equals("Đặt bàn")) {
            if (tenBan != null) {
                Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
                if (b.getTrangThai().equals("Trống")) {
                    giaoDienDatBan();
                } else {
                    MsgBox.alert(null, "Vui lòng chọn bàn trống để đặt bàn", 2);
                }

            } else {
                MsgBox.alert(null, "Vui lòng chọn bàn để đặt bàn", 2);
            }

        } else if (btnDatBan.getText().equals("Hủy đặt bàn")) {
            if (MsgBox.confirm(null, "Ban muốn hủy đặt " + tenBan)) {
                Ban b = updateBanTrong();
                bdao.update(b);
                btnDatBan.setText("Đặt bàn");
                mnDatBan.setText("Đặt bàn");
                KhuVuc kv = kvdao.selectById(b.getKhuVuc());
                fillBan(kv.getTenKV());
                clickBan();
                List<HoaDon> list = hddao.selectByMaBan(b.getMaBan());
                for (HoaDon hd : list) {
                    if (hd.getThoiGianTaoHD() == null) {
                        hddao.delete(hd.getMaHD());
                    }
                }
                MsgBox.alert(null, "Hủy đặt bàn thành công", JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }

    public void datBanOK() {
        if (checkValidateFormKH()) {
            insertKH();
            HoaDon hd = getFormKH();
            try {
                hddao.insert(hd);
            } catch (Exception e) {
            }
            dgDatBan.setVisible(false);
            Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
            Ban bUpdate = new Ban();
            bUpdate.setMaBan(b.getMaBan());
            bUpdate.setTenBan(b.getTenBan());
            bUpdate.setKhuVuc(b.getKhuVuc());
            bUpdate.setTrangThai("Đã đặt");
            bdao.update(bUpdate);

            Ban bfill = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
            pn_MenuKV.setVisible(false);
            KhuVuc kv = kvdao.selectById(bfill.getKhuVuc());
            fillBan(kv.getTenKV());
            clickBan();
            btnDatBan.setText("Hủy đặt bàn");
            mnDatBan.setText("Hủy đặt bàn");
        }

    }

    public boolean checkValidateFormChonSL() {
        if (txtSoLuong.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập số lượng!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        int sl;
        try {
            sl = Integer.parseInt(txtSoLuong.getText());
            if (sl <= 0) {
                MsgBox.alert(this, "Số lượng phải lớn hơn 0!", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Số lượng phải là số!", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    public void xoaSPtrongCTHD() {
        int row = tblHoaDon.getSelectedRow();
        String tenSP = null;
        for (int i = 0; i < tblHoaDon.getRowCount(); i++) {
            tenSP = (String) tblHoaDon.getValueAt(row, 1);
        }
        if (MsgBox.confirm(null, "Bạn muốn xóa sản phẩm " + tenSP)) {
            int maHD = 0;
            Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());

            List<HoaDon> list = hddao.selectByMaBan(b.getMaBan());
            for (HoaDon hoaDon : list) {
                if (hoaDon.getNgayThanhToan() == null) {
                    maHD = hoaDon.getMaHD();
                }
            }

            SanPham sp = spdao.selectByTenSPTraveMaSP(tenSP);
            List<ChiTietHoaDon> listcthd = cthddao.selectByMaHD(maHD);
            for (ChiTietHoaDon cthd : listcthd) {
                if (cthd.getMaSP().equals(sp.getMaSP())) {
                    cthddao.delete(cthd.getMaCTHD());
                    fillTable();
                    clickBan();
                    HoaDon hd = new HoaDon(maHD, tongTienTuTable());
                    hddao.updateTongTien(hd);
                }
            }
            List<ChiTietHoaDon> listct = cthddao.selectByMaHD(maHD);
            if (listct.size() == 0) {
                hddao.delete(maHD);
                Ban bUp = updateBanTrong();
                bdao.update(bUp);
                KhuVuc kv = kvdao.selectById(bUp.getKhuVuc());
                fillBan(kv.getTenKV());
                checkFillDuoiTable = false;
                clickBan();
            }
        }
    }

    private void giaoDienDatBan() {

        dgDatBan = new JDialog();
        dgDatBan.setUndecorated(true);
        dgDatBan.setPreferredSize(new Dimension(465, 365));
        dgDatBan.setSize(465, 365);

        JPanel pannelDatBan = new JPanel();
        pannelDatBan.setLayout(null);
        pannelDatBan.setPreferredSize(new Dimension(465, 365));
        pannelDatBan.setSize(465, 365);
        pannelDatBan.setBackground(Color.WHITE);

        JLabel jlbltt = new JLabel("Thông tin khách hàng");
        jlbltt.setPreferredSize(new Dimension(465, 35));
        jlbltt.setSize(new Dimension(465, 35));
        jlbltt.setBackground(new java.awt.Color(255, 255, 255));
        jlbltt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlbltt.setForeground(new java.awt.Color(97, 67, 67));
        jlbltt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbltt.setLocation(0, 0);

        JLabel jlbltenKH = new JLabel();
        jlbltenKH.setPreferredSize(new Dimension(67, 40));
        jlbltenKH.setSize(new Dimension(67, 40));
        jlbltenKH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbltenKH.setForeground(new java.awt.Color(97, 67, 67));
        jlbltenKH.setText("Tên KH:");
        jlbltenKH.setLocation(36, 53);

        JLabel jlblSDT = new JLabel();
        jlblSDT.setPreferredSize(new Dimension(67, 40));
        jlblSDT.setSize(new Dimension(67, 40));
        jlblSDT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblSDT.setForeground(new java.awt.Color(97, 67, 67));
        jlblSDT.setText("SĐT:");
        jlblSDT.setLocation(36, 101);

        JLabel jlblGT = new JLabel();
        jlblGT.setPreferredSize(new Dimension(83, 40));
        jlblGT.setSize(new Dimension(83, 40));
        jlblGT.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jlblGT.setForeground(new java.awt.Color(97, 67, 67));
        jlblGT.setText("Giới Tính:");
        jlblGT.setLocation(36, 149);

        JLabel jlblGD = new JLabel();
        jlblGD.setPreferredSize(new Dimension(80, 40));
        jlblGD.setSize(new Dimension(80, 40));
        jlblGD.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jlblGD.setForeground(new java.awt.Color(97, 67, 67));
        jlblGD.setText("Giờ đến:");
        jlblGD.setLocation(36, 241);

        txtTenKH = new JTextField();
        txtTenKH.setPreferredSize(new Dimension(300, 40));
        txtTenKH.setSize(new Dimension(300, 40));
        txtTenKH.setBackground(new java.awt.Color(230, 213, 193));
        txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenKH.setLocation(121, 55);

        txtSoDT = new JTextField();
        txtSoDT.setPreferredSize(new Dimension(300, 40));
        txtSoDT.setSize(new Dimension(300, 40));
        txtSoDT.setBackground(new java.awt.Color(230, 213, 193));
        txtSoDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoDT.setLocation(121, 103);

        txtGioiDen = new JTextField();
        txtGioiDen.setPreferredSize(new Dimension(240, 40));
        txtGioiDen.setSize(new Dimension(240, 40));
        txtGioiDen.setBackground(new java.awt.Color(230, 213, 193));
        txtGioiDen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGioiDen.setLocation(121, 243);
        txtGioiDen.setEditable(false);

        btnChonGio = new JButton();
        btnChonGio.setPreferredSize(new Dimension(50, 40));
        btnChonGio.setSize(new Dimension(50, 40));
        btnChonGio.setBackground(new java.awt.Color(191, 158, 117));
        btnChonGio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnChonGio.setForeground(new java.awt.Color(255, 255, 255));
        btnChonGio.setText("...");
        btnChonGio.setHorizontalAlignment(SwingConstants.CENTER);
        btnChonGio.setVerticalAlignment(SwingConstants.CENTER);
        btnChonGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeGioDen.showPopup(dgDatBan, 100, 100);
            }
        });
        btnChonGio.setLocation(371, 243);
        timeGioDen.setDisplayText(txtGioiDen);

        btgGioiTinh = new ButtonGroup();
        rdoNam = new JRadioButton();
        rdoNam.setPreferredSize(new Dimension(62, 30));
        rdoNam.setSize(new Dimension(62, 30));
        rdoNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoNam.setForeground(new java.awt.Color(97, 67, 67));
        rdoNam.setText("Nam");
        rdoNam.setLocation(125, 157);
        btgGioiTinh.add(rdoNam);

        rdoNu = new JRadioButton();
        rdoNu.setPreferredSize(new Dimension(62, 30));
        rdoNu.setSize(new Dimension(62, 30));
        rdoNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoNu.setForeground(new java.awt.Color(97, 67, 67));
        rdoNu.setText("Nữ");
        rdoNu.setLocation(204, 157);
        btgGioiTinh.add(rdoNu);

        btnOkDatBan = new JButton();
        btnOkDatBan.setPreferredSize(new Dimension(150, 40));
        btnOkDatBan.setSize(new Dimension(150, 40));
        btnOkDatBan.setBackground(new java.awt.Color(191, 158, 117));
        btnOkDatBan.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnOkDatBan.setForeground(new java.awt.Color(255, 255, 255));
        btnOkDatBan.setText("OK");
        btnOkDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkDatBanActionPerformed(evt);
            }
        });
        btnOkDatBan.setLocation(80, 303);

        btnHuyDatBan = new JButton();
        btnHuyDatBan.setPreferredSize(new Dimension(150, 40));
        btnHuyDatBan.setSize(new Dimension(150, 40));
        btnHuyDatBan.setBackground(new java.awt.Color(191, 158, 117));
        btnHuyDatBan.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnHuyDatBan.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyDatBan.setText("Huỷ");
        btnHuyDatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dgDatBan.setVisible(false);
            }
        });
        btnHuyDatBan.setLocation(248, 303);

        JLabel jlblND = new JLabel();
        jlblND.setPreferredSize(new Dimension(92, 40));
        jlblND.setSize(new Dimension(92, 40));
        jlblND.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlblND.setForeground(new java.awt.Color(97, 67, 67));
        jlblND.setText("Ngày đến:");
        jlblND.setPreferredSize(new java.awt.Dimension(38, 40));
        jlblND.setLocation(36, 195);

        dateNgayDen = new JDateChooser();
        dateNgayDen.setPreferredSize(new Dimension(285, 40));
        dateNgayDen.setSize(285, 40);
        dateNgayDen.setBackground(new java.awt.Color(230, 213, 193));
        dateNgayDen.setDateFormatString("yyyy-MM-dd");
        dateNgayDen.setLocation(134, 195);

        pannelDatBan.add(jlbltt);
        pannelDatBan.add(txtTenKH);
        pannelDatBan.add(jlblGT);
        pannelDatBan.add(jlbltenKH);
        pannelDatBan.add(jlblSDT);
        pannelDatBan.add(txtSoDT);
        pannelDatBan.add(rdoNam);
        pannelDatBan.add(rdoNu);
        pannelDatBan.add(btnOkDatBan);
        pannelDatBan.add(btnHuyDatBan);
        pannelDatBan.add(jlblND);
        pannelDatBan.add(dateNgayDen);
        pannelDatBan.add(jlblGD);
        pannelDatBan.add(txtGioiDen);
        pannelDatBan.add(btnChonGio);

        dgDatBan.add(pannelDatBan);
        dgDatBan.setLocationRelativeTo(null);
        dgDatBan.setVisible(true);
        focusInputDatBan();
        setBorderInputDatBan();
    }

    private void focusInputDatBan() {
        Border borderNhanVao = BorderFactory.createLineBorder(new Color(227, 188, 140), 10, true);
        Border borderKhongNhan = BorderFactory.createLineBorder(new Color(230, 213, 193), 10, true);
        txtTenKH.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtTenKH.setBackground(new Color(227, 188, 140));
                txtTenKH.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtTenKH.setBackground(new Color(230, 213, 193));
                txtTenKH.setBorder(borderKhongNhan);
            }
        });
        txtSoDT.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtSoDT.setBackground(new Color(227, 188, 140));
                txtSoDT.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtSoDT.setBackground(new Color(230, 213, 193));
                txtSoDT.setBorder(borderKhongNhan);
            }
        });
        txtGioiDen.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                txtGioiDen.setBackground(new Color(227, 188, 140));
                txtGioiDen.setBorder(borderNhanVao);
            }

            @Override
            public void focusLost(FocusEvent e) {
                txtGioiDen.setBackground(new Color(230, 213, 193));
                txtGioiDen.setBorder(borderKhongNhan);
            }
        });

    }

    private void setBorderInputDatBan() {
        Border border = BorderFactory.createLineBorder(new Color(230, 213, 193), 10, true);
        txtTenKH.setBorder(border);
        txtSoDT.setBorder(border);
        txtGioiDen.setBorder(border);
    }

    private void insertKH() {
        KhachHang kh = new KhachHang();
        maKH = checkTrungMaKH(maKHCheck);
        kh.setMaKH(maKH);
        kh.setDiaChi(null);
        kh.setEmail(null);
        kh.setGioiTinh(rdoNu.isSelected());
        kh.setTenKH(txtTenKH.getText());
        kh.setSDT(txtSoDT.getText());
        khdao.insert(kh);
    }

   private HoaDon getFormKH() {
        HoaDon hd = new HoaDon();

        String ngay = XDate.toString(dateNgayDen.getDate(), "yyyy-MM-dd");
        String ngayDatBan = ngay + " " + txtGioiDen.getText() + ":00";
        hd.setNgayDatBan(XDate.toDate(ngayDatBan, "yyyy-MM-dd HH:mm:ss"));
        hd.setNgayThanhToan(null);
        hd.setThoiGianTaoHD(null);
        hd.setThoiGianThanhToan(null);
        hd.setTongTien(0.0);
        hd.setTrangThai(false);
        hd.setMaNV("nghiatv");
        Ban b = bdao.selectByTenBanTraVeBan(tenBan, Auth.user.getMaDV());
        hd.setMaBan(b.getMaBan());
        hd.setMaKH(maKH);

        return hd;
    }

    private String checkTrungMaKH(String id) {
        List<KhachHang> list = khdao.selectAll();
        String maKH = id;
        if (list.isEmpty()) {
            maKH = maKH + "01";
        } else {
            String maKHCuoiList = list.get(list.size() - 1).getMaKH();
            int sauMaKH = Integer.valueOf(maKHCuoiList.substring(2, maKHCuoiList.length())) + 1;
            if (sauMaKH < 10) {
                maKH = maKH + "0" + sauMaKH;
            } else {
                maKH = maKH + sauMaKH;
            }
        }
        return maKH;
    }

    boolean checkValidateFormKH() {
        if (txtTenKH.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập họ và tên!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txtSoDT.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng nhập số điện thoại!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            long sdt = Long.parseLong(txtSoDT.getText());
            if (sdt < 0) {
                MsgBox.alert(this, "Số điện thoại không được là số âm!", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Số điện thoại phải là số!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        String sdt10so = "\\d{10}";
        if (!txtSoDT.getText().matches(sdt10so)) {
            MsgBox.alert(this, "Số điện thoại phải là 10 số!", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        String patternSDT = "^(0[3-9])\\d{8}$";
        if (!txtSoDT.getText().matches(patternSDT)) {
            MsgBox.alert(this, "Số điện thoại không đúng định dạng!", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (!rdoNam.isSelected() && !rdoNu.isSelected()) {
            MsgBox.alert(this, "Vui lòng chọn giới tính!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (dateNgayDen.getDate() == null) {
            MsgBox.alert(this, "Vui lòng chọn ngày đến!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        Date now = new Date();
        String ngay = XDate.toString(dateNgayDen.getDate(), "yyyy-MM-dd");
        Date ngaylan2 = XDate.toDate(ngay, "yyyy-MM-dd");

        if (ngaylan2.before(now)) {
            if (!ngay.equals(XDate.toString(now, "yyyy-MM-dd"))) {
                MsgBox.alert(this, "Ngày đến phải sau hoặc là ngày hiện tại", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        if (txtGioiDen.getText().isEmpty()) {
            MsgBox.alert(this, "Vui lòng chọn giờ đến!", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        LocalTime gioNow = LocalTime.now(); //XDate.toDate(txtGioiDen.getText() + ":00", "HH:mm:ss");
        LocalTime gio = LocalTime.parse(txtGioiDen.getText() + ":00");
        if (ngay.equals(XDate.toString(now, "yyyy-MM-dd"))) {
            if (gio.isBefore(gioNow)) {
                MsgBox.alert(this, "Giờ đến phải sau giờ hiện tại", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        return true;
    }

    private void datLaiBanKhiQuaGio() {
        Thread t = new Thread(() -> {
            for (int i = 0; true; i++) {
                List<HoaDon> listHD = hddao.selectAll();
                Date now = new Date();
                LocalTime timeNow = LocalTime.now();
                String ngay = XDate.toString(now, "yyyy-MM-dd");
                for (HoaDon hoaDon : listHD) {
                    if (!hoaDon.isTrangThai() && hoaDon.getThoiGianTaoHD() == null && hoaDon.getNgayDatBan() != null) {
                        String ngayHD = XDate.toString(hoaDon.getNgayDatBan(), "yyyy-MM-dd");
                        String gioHD = XDate.toString(hoaDon.getNgayDatBan(), "HH:mm:ss");
                        LocalTime timeHD = LocalTime.parse(gioHD);
                        if (ngay.equals(ngayHD)) {
                            int checkGio = (int) (timeNow.toSecondOfDay() - timeHD.toSecondOfDay());
                            if (checkGio >= 60) {
                                Ban b = bdao.selectById(hoaDon.getMaBan());
                                if (MsgBox.confirm(this, b.getTenBan() + " đã qua giờ đặt. Bạn có muốn đặt tiếp hay không?")) {
                                    HoaDon hd = new HoaDon(idHoaDon(b.getTenBan()), now);
                                    hddao.updateNgayDBCuaHD(hd);
                                } else {
                                    hddao.delete(hoaDon.getMaHD());
                                    Ban bnew = new Ban();
                                    bnew.setMaBan(b.getMaBan());
                                    bnew.setKhuVuc(b.getKhuVuc());
                                    bnew.setTenBan(b.getTenBan());
                                    bnew.setTrangThai("Trống");
                                    bdao.update(bnew);

                                    tenBan = null;
                                    pn_MenuKV.setVisible(false);
                                    KhuVuc kv = kvdao.selectById(b.getKhuVuc());
                                    fillBan(kv.getTenKV());
                                    clickBan();
                                }
                            }
                        }
                    }
                }
                try {
                    Thread.sleep(5 * 1000);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }

        });
        t.start();
    }

    private void suaSLSPtrongCTHD(int sl, String ghichu) {

        dgSuaSL = new JDialog();
        dgSuaSL.setUndecorated(true);
        dgSuaSL.setPreferredSize(new Dimension(500, 250));
        dgSuaSL.setSize(500, 250);

        JPanel pannel = new JPanel();
        pannel.setLayout(null);
        pannel.setPreferredSize(new Dimension(500, 250));
        pannel.setSize(500, 250);
        pannel.setBackground(Color.WHITE);

        JLabel jLabelSL = new JLabel("Số lượng:");
        jLabelSL.setPreferredSize(new Dimension(90, 35));
        jLabelSL.setSize(90, 40);
        jLabelSL.setFont(new Font("Roboto", Font.PLAIN, 20));
        jLabelSL.setForeground(new Color(0, 0, 0));
        jLabelSL.setLocation(30, 40);

        JLabel jLabelGC = new JLabel("Ghi chú:");
        jLabelGC.setPreferredSize(new Dimension(90, 35));
        jLabelGC.setSize(90, 40);
        jLabelGC.setFont(new Font("Roboto", Font.PLAIN, 20));
        jLabelGC.setForeground(new Color(0, 0, 0));
        jLabelGC.setLocation(30, 88);

        txtSuaSoLuong = new JTextField();
        txtSuaSoLuong.setPreferredSize(new Dimension(340, 40));
        txtSuaSoLuong.setBackground(new Color(227, 188, 140));
        txtSuaSoLuong.setOpaque(true);
        txtSuaSoLuong.setFont(new Font("Roboto", Font.PLAIN, 20));
        txtSuaSoLuong.setHorizontalAlignment(SwingConstants.RIGHT);
        Border border = BorderFactory.createLineBorder(new Color(227, 188, 140), 10, true);
        txtSuaSoLuong.setSize(340, 40);
        txtSuaSoLuong.setLocation(120, 40);
        txtSuaSoLuong.setBorder(border);
        txtSuaSoLuong.setText(sl + "");

        txtSuaGhiChu = new JTextField();
        txtSuaGhiChu.setPreferredSize(new Dimension(340, 40));
        txtSuaGhiChu.setBackground(new Color(227, 188, 140));
        txtSuaGhiChu.setFont(new Font("Roboto", Font.PLAIN, 20));
        txtSuaGhiChu.setOpaque(true);
        txtSuaGhiChu.setSize(340, 40);
        txtSuaGhiChu.setLocation(120, 90);
        txtSuaGhiChu.setText(ghichu);
        txtSuaGhiChu.setBorder(border);

        btnOkSuaSoLuong = new JButton("OK");
        btnOkSuaSoLuong.setPreferredSize(new Dimension(150, 40));
        btnOkSuaSoLuong.setSize(150, 40);
        btnOkSuaSoLuong.setBackground(new Color(191, 158, 117));
        btnOkSuaSoLuong.setFont(new Font("Roboto", Font.BOLD, 20));
        btnOkSuaSoLuong.setForeground(new Color(255, 255, 255));
        btnOkSuaSoLuong.setLocation(95, 160);
        btnOkSuaSoLuong.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                btnOKSuaSoLuongActionPerformed(e);
            }
        });

        JButton btnHuySuaSoLuong = new JButton("Hủy");
        btnHuySuaSoLuong.setPreferredSize(new Dimension(150, 40));
        btnHuySuaSoLuong.setSize(150, 40);
        btnHuySuaSoLuong.setBackground(new Color(191, 158, 117));
        btnHuySuaSoLuong.setFont(new Font("Roboto", Font.BOLD, 20));
        btnHuySuaSoLuong.setForeground(new Color(255, 255, 255));
        btnHuySuaSoLuong.setLocation(255, 160);
        btnHuySuaSoLuong.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dgSuaSL.setVisible(false);
            }
        });

        pannel.add(jLabelSL);
        pannel.add(txtSuaSoLuong);
        pannel.add(jLabelGC);
        pannel.add(txtSuaGhiChu);
        pannel.add(btnOkSuaSoLuong);
        pannel.add(btnHuySuaSoLuong);
        dgSuaSL.add(pannel);
        dgSuaSL.setVisible(true);
        dgSuaSL.setLocationRelativeTo(null);
    }

    public void okSuaSoLuongCTHD() {
        if (checkValidateFormChonSL()) {
            List<ChiTietHoaDon> list = cthddao.selectByMaHD(idHoaDon(tenBan));
            String maSP = (String) tblHoaDon.getValueAt(intOkSuaSL, 0);
            for (ChiTietHoaDon cthd : list) {
                if (cthd.getMaSP().equals(maSP)) {
                    SanPham sp = spdao.selectById(cthd.getMaSP());
                    ChiTietHoaDon cthdnew = new ChiTietHoaDon();
                    cthdnew.setMaCTHD(cthd.getMaCTHD());
                    cthdnew.setMaHD(cthd.getMaHD());
                    cthdnew.setMaSP(cthd.getMaSP());
                    cthdnew.setSoLuong(Integer.valueOf(txtSuaSoLuong.getText()));
                    cthdnew.setTongTienSP(Integer.valueOf(txtSuaSoLuong.getText()) * sp.getGia());
                    cthddao.update(cthdnew);
                    dgSuaSL.setVisible(false);
                    fillTable();
                    clickBan();
                }
            }
            double tongTien = 0;
            List<ChiTietHoaDon> listnew = cthddao.selectByMaHD(idHoaDon(tenBan));
            for (ChiTietHoaDon chiTietHoaDon : listnew) {
                tongTien += chiTietHoaDon.getTongTienSP();
            }
            HoaDon hdUpate = new HoaDon(idHoaDon(tenBan), tongTien);
            hddao.updateTongTien(hdUpate);
        }
    }
}
